LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := focaltech_ats.ko
LOCAL_MODULE_CLASS := SHARED_LIBRARIES
LOCAL_MODULE_PATH := $(TARGET_OUT_VENDOR)/lib/modules
LOCAL_STRIP_MODULE := keep_symbols

# Use intermediates directory
KERNEL_MODULE_INTERMEDIATE := $(call intermediates-dir-for,SHARED_LIBRARIES,focaltech_ats)
LOCAL_GENERATED_SOURCES := $(KERNEL_MODULE_INTERMEDIATE)/focaltech_ats.ko

include $(BUILD_PREBUILT)

ifeq ($(TARGET_BUILD_VARIANT),user)
DEBUGMODE := BUILD=no
else
DEBUGMODE := $(DEBUGMODE)
endif

# Build rule for the generated .ko file
$(KERNEL_MODULE_INTERMEDIATE)/focaltech_ats.ko: $(TARGET_PREBUILT_KERNEL)
	$(MAKE) -C $(LOCAL_PATH) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) $(DEBUGMODE) KDIR=$(PRODUCT_OUT)/obj/KERNEL O=$(KERNEL_MODULE_INTERMEDIATE) clean
	$(MAKE) -C $(LOCAL_PATH) ARCH=$(TARGET_KERNEL_ARCH) CROSS_COMPILE=$(KERNEL_CROSS_COMPILE) $(DEBUGMODE) KDIR=$(PRODUCT_OUT)/obj/KERNEL O=$(KERNEL_MODULE_INTERMEDIATE)
	$(TARGET_STRIP) -d --strip-unneeded $@